name: Build and Deploy
on:
  discussion:
  discussion_comment:

jobs:
  label_discussion:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.discussion.title }}
          echo ${{ github.event.discussion.body }}
          echo ${{ github.event.discussion.user.name }}
