name: Build and Deploy
on:
  discussion:
  discussion_comment:

permissions:
  contents: write

jobs:
  label_discussion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ github.event.discussion.title }} > discussion.txt
          echo ${{ github.event.discussion.body }}
          echo ${{ github.event.discussion.user.login }}
          echo ${{ github.event.discussion.user.name }}
          echo ${{ github.event.discussion.answer_html_url }}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
