name: Rating

on:
  discussion:
    types: [created, edited]

permissions:
  discussions: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Add Label
        run: deno run -A actions/add_label.ts
        env:
          repo: ${{ github.repository }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          discussionId: ${{ github.event.discussion.node_id }}

  nsfw-rating:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno install --node-modules-dir=auto --allow-scripts=npm:sharp@0.33.5,npm:@tensorflow/tfjs-node@4.21.0,npm:core-js@3.29.1

      - name: Rating Images
        env:
          actionId: ${{ github.run_id }}
          jobId: ${{ github.job}}
          repo: ${{ github.repository }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          discussionId: ${{ github.event.discussion.node_id }}
          discussionBody: ${{ github.event.discussion.body }}
        run: deno run --node-modules-dir=auto -A actions/nsfw_rating.ts

  discussion-rating:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Install Qwen2.5 7B
        run: ollama pull qwen2.5:7b

      - name: Rating discussion
        env:
          actionId: ${{ github.run_id }}
          jobId: ${{ github.job}}
          repo: ${{ github.repository }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          discussionId: ${{ github.event.discussion.node_id }}
          discussionTitle: ${{ github.event.discussion.title }}
          discussionBody: ${{ github.event.discussion.body }}
        run: deno run -A actions/rating.ts

  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Install Qwen2.5 7B
        run: ollama pull qwen2.5:7b

      - name: Summary discussion
        env:
          actionId: ${{ github.run_id }}
          jobId: ${{ github.job}}
          owner: ${{ github.repository_owner }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          discussionId: ${{ github.event.discussion.node_id }}
          discussionTitle: ${{ github.event.discussion.title }}
          discussionBody: ${{ github.event.discussion.body }}
        run: deno run -A actions/summary.ts
