name: Save Discussion

on:
  discussion:
  discussion_comment:

permissions:
  contents: write

jobs:
  save-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: |
          currentTime=$(date +"%s")
          mkdir -p discussions
          echo $event > discussions/${{ github.event.discussion.number }}-$currentTime.json
        env:
          event: ${{ toJson(github.event) }}

      - name: Commit files
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add .
          git commit -m "save discussion ${{ github.event.discussion.number }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
